---
version: "3"

services:

  who1:
    image: "emilevauge/whoami"
    #ports:
    #  - "8081:8080"
    #volumes:
    #  - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - "traefik0"
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.01'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 20M
      labels:
        - "traefik.backend=who1"
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.frontend.rule=PathPrefixStrip:/who1/"
        - "traefik.docker.network=traefik0"

  who2:
    image: "emilevauge/whoami"
    #ports:
    #  - "8081:8080"
    #volumes:
    #  - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - "traefik0"
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.01'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 20M
      labels:
        - "traefik.backend=who2"
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.frontend.rule=PathPrefixStrip:/who2/"
        - "traefik.docker.network=traefik0"

networks:
  traefik0:
    external: true