version: "3.1"

services:
  docker-proxy:
    image: rancher/socat-docker
    network:
      - docker_proxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  traefik:
    image: traefik:1.2.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./infra/traefik/traefik.toml:/traefik.toml"
      - "./infra/traefik/acme.json:/acme.json"
    networks:
      - traefik0
      - docker_proxy
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.30'
          memory: 128M
        reservations:
          cpus: '0.10'
          memory: 50M

networks:
  traefik0:
    external: true

networks:
  docker_proxy:
    external: true