---
version: "3.1"

services:

  docker-proxy:
    image: rancher/socat-docker
    network:
      - docker_proxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  traefik:
    image: containous/traefik:v1.2.3-alpine
    ports:
      - "80:80"
      - "443:443"
      #- "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./infra/traefik/traefik.toml:/traefik.toml"
      - "./infra/traefik/acme.json:/acme.json"
    networks:
      - "traefik0"
      - "docker_proxy"
    labels: {}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.30'
          memory: 128M
        reservations:
          cpus: '0.10'
          memory: 50M
      labels:
        traefik.enable: "true"
        traefik.docker.network: traefik0
        traefik.port: 8080
        traefik.backend.loadbalancer.sticky: "true"
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.rule: "PathPrefixStrip:/traefik/"

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - "traefik0"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.20'
          memory: 128M
        reservations:
          cpus: '0.10'
          memory: 50M
      labels:
        traefik.enable: "false"
        #traefik.docker.network: traefik0
        #traefik.port: 8080
        #traefik.backend.loadbalancer.sticky: "true"
        #traefik.frontend.passHostHeader: "true"
        #traefik.frontend.rule: Host:swarm.ginsys.io
        #traefik.frontend.auth.basic: "toor:$apr1$B5HlT1Ke$BrwFqaWGUuRBIlKwOUnxo/"

networks:
  traefik0:
    external: true
		
networks:
  docker_proxy:
    external: true
